name: Node.js build & test

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
       node-version: 18
       
    - run: npm install
    - run: npm test
  
  
  # - run: npm install mocha --save-dev
  #  - run: npm install
  #- run: npm run build --if-present
  #  - run: npm test
